#+Title: Emacs Configuration

* Preparation
** Use lexical-binding

Since Emacs 31, Emacs will emit a runtime warning when loading ~.el~ files
without the ~lexical binding~ file-local cookie.

The cookie ~;; -*- lexical-binding: t; -*-~ must sit on the very first
physical line of the generated ~.el~ file to take effect.

#+begin_src emacs-lisp
  ;; -*- lexical-binding: t -*-
#+end_src

** Configuration setup

This is the configuration file for my Emacs.

Some Emacs settings needs frequenctly modification, which are listed
in Table [[conf-table]] so that they can be changed easily. Other
configurations can also be modified by the emacs-lisp source code
blocks in this file.

#+CAPTION: General Configuration
#+NAME: conf-table
| Field              | Value   | Description                |
|--------------------+---------+----------------------------|
| font               | default |                            |
| font-size          | 15      | font height in units of pt |
| cjk-font           | default |                            |
| python-interpreter | default | default for auto-detection |
| longitude          | 121     | calendar-longitude         |
| latitude           | 31      | calendar-latitude          |
| backup-dir         | default | backup directory           |

** Macro definition

Get result from Table [[conf-table]].

#+begin_src emacs-lisp
  (defmacro get-conf! (key)
    "Access to value in conf-table."
      `(cadr (assoc ,key conf-table))
    )
  ;;(macroexpand-1 '(get-conf! "font"))
#+end_src

Run function silently.

#+begin_src emacs-lisp
  (defun silent-forward (func &rest args)
    "Run func with args while inhibiting its message display."
    (let ((inhibit-message t)
          (message-log-max nil))
      (apply func args)
      )
    )

  ;; The same as silent-forward using macro.
  (defmacro silent-forward!(&rest args)
    "Run func with args while inhibiting its message display."
    `(let ((inhibit-message t)
           (message-log-max nil))
       ,args
      )
    )

  ;; The following two statements are equal:
  ;; (silent-forward 'message "Message")
  ;; (silent-forward! message "Message")
  ;; To inspect into this macro, use macorexpand-1:
  ;; (macroexpand-1 '(message "Message"))
#+end_src

* Preference
** Personal info

Set =user-full-name.=

#+BEGIN_SRC emacs-lisp
  (setq user-full-name "Zhen NI")
#+END_SRC

** Package management
*** Use Melpa

Add melpa to package management system.

#+begin_src emacs-lisp
  ;; Added by Package.el. This must come before configurations
  ;; of installed packages. Don't delete this line. If you
  ;; don't want it, just comment it out by adding a semicolon
  ;; to the start of the line. You may delete these
  ;; explanatory comments.
  (require 'package)
  (setq package-archives
        '(("gnu" . "https://mirrors.ustc.edu.cn/elpa/gnu/")
          ("nongnu" . "https://mirrors.ustc.edu.cn/elpa/nongnu/")
          ("melpa" . "https://mirrors.ustc.edu.cn/elpa/melpa/")
          ("melpa-stable" . "https://mirrors.ustc.edu.cn/elpa/melpa-stable/")))
  (package-initialize)
#+end_src

#+RESULTS:

*** Use use-package

Since version 29, ~use-package~ has been built into Emacs.

For any reasons if =use-package= needs installation, the following code
can be used.

#+begin_src emacs-lisp
  ;; (unless (package-installed-p 'use-package)
  ;;   (package-install 'use-package))
#+end_src

Package ~keyring~ is essential for installing other packages. Otherwise, can
use `(setq package-check-signature nil)` as a solution. See [[https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html][this
page]]. Here, a temporarily solution is provided by disabling signature
check, which is given by [[https://stackoverflow.com/questions/78381013/failed-to-verify-signature-archive-contents-sig-problem-with-emacs][stackoverflow]].
#+begin_src emacs-lisp
  ;; (setq package-check-signature-backup package-check-signature)
  (setq package-check-signature nil)
  ;; (package-refresh-contents)
  ;; (package-install 'gnu-elpa-keyring-update)
  ;; (gnu-elpa-keyring-update)
  ;; It seems the above code is of no use... we just disable signature
  ;; check.
  ; (setq package-check-signature package-check-signature-backup)
#+end_src

** Startup screen
*** Disable builtin startup screen

Turn off the startup screen. Type =M-x display-about-screen= to
open it manually if you want.

#+begin_src emacs-lisp
  (setq inhibit-startup-screen t)
#+end_src

*** Use Dashboard

Make sure dashboard is installed.
#+begin_src emacs-lisp
  (use-package dashboard
	       :ensure t
	       )
#+end_src

Dashboard settings.

#+begin_src emacs-lisp
  ; (require 'dashboard) ;; not necessray as use-package is used
  (dashboard-setup-startup-hook)
  (setq dashboard-banner-logo-title "Nice day!")
  (setq dashboard-startup-banner 'official) ;;
  (setq dashboard-items '(
                          (projects . 5)
                          (bookmarks . 5)  ;; number of listed bookmarks
                          (recents  . 5)  ;; number of listed recent files
                          )
        )
#+end_src

Provide a function =(dashboard)= to goto dashboard. See [[https://github.com/emacs-dashboard/emacs-dashboard/issues/236#issue-688633919][this link]]
for more details.

#+begin_src emacs-lisp
  (defun dashboard nil
    (interactive)
    (if (get-buffer "*dashboard*")
        (switch-to-buffer "*dashboard*")
        (dashboard-refresh-buffer))
    )
#+end_src

Use =<f5>= to refresh dashboard buffer.

#+begin_src emacs-lisp
  (add-hook 'dashboard-mode-hook
            (lambda () (local-set-key [f5]
                                      'dashboard-refresh-buffer)))
#+end_src

** Internet connection

Use clash proxy

#+begin_src emacs-lisp
  (defvar clash-proxy-enabled nil)

  (defun clash-proxy-sentinel (proc msg)
    (when (string-match "open" msg)
      ;; Use clash proxy
      (setq url-proxy-services
            '(("http" . "127.0.0.1:7890")
              ("https" . "127.0.0.1:7890")
              ("no_proxy" . "localhost,127.0.0.1"))
            clash-proxy-enabled t)
      (message "Clash port 7890 detected, proxy enabled."))
    (when (string-match "failed" msg)
      (setq url-proxy-services nil
            clash-proxy-enabled nil)
      (message "Clash port 7890 not available, proxy disabled."))
    (delete-process proc))

  (defun enable-clash-proxy ()
    "Check Clash port 7890 and toggle url-proxy-services automatically."
    (interactive)
    (make-network-process
     :name "clash-proxy"
     :host "127.0.0.1"
     :service 7890
     :nowait t
     :sentinel #'clash-proxy-sentinel))

  (enable-clash-proxy)
#+end_src

** Misc

Turn off the annoying bell.

#+begin_src emacs-lisp
  (setq visible-bell t)
#+end_src

Replace yes-no answers with y-n.

#+begin_src emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+end_src

Stop always popping warning messages.
#+begin_src emacs-lisp
  (setq warning-minimum-level :error)
#+end_src

* Appearance
** Color Theme
*** COMMENT Set by manually specified time

Set color theme by time. The theme is set to =tango= from 8:00
to 18:00, and set to =tango-dark= from 18:00 to 8:00. The code
is modified from [[https://stackoverflow.com/a/14760833/2731421][this answer on Github]].

#+begin_src emacs-lisp
  ;; See https://stackoverflow.com/a/14760833/2731421 for more
  ;; information.

  (setq current-theme nil)
  (setq theme-light 'tango)
  (setq theme-dark 'tango-dark)


  (defun synchronize-theme-helper (new-theme)
    "Set the current theme to new-theme."
    (if (equal current-theme new-theme) ()
      (disable-theme current-theme)
      (load-theme new-theme t)
      (setq current-theme new-theme)
      ))

  (defun synchronize-theme ()
    "Set theme by time."
    (let ((hour (string-to-number
                 (substring (current-time-string) 11 13))))
      (if (member hour (number-sequence 8 17))
          (synchronize-theme-helper 'theme-light)
        (synchronize-theme-helper 'theme-dark)
        )
      ))

  ;; Although (run-with-timer) can set the theme automatically
  ;; after initializaion of emacs, we would like the set the
  ;; theme at startup before loading other packages like
  ;; org-indent mode so that these modes can corrently set the
  ;; style according to the active theme.
  (synchronize-theme)

  ;; Check every 10 minutes.
  (run-with-timer 0 600 'synchronize-theme)
#+end_src

*** Set by sunrise and sunset time automatically

Use light theme when sun rises and dark theme when
sun sets.

#+begin_src emacs-lisp :var conf-table=conf-table
  (setq current-theme nil)
  (setq theme-light 'tango)
  (setq theme-dark 'tango-dark)

  (defun change-theme (new-theme)
    "Set the current theme to new-theme."
    (unless (equal current-theme new-theme)
      (disable-theme current-theme)
      (load-theme new-theme t)
      (setq current-theme new-theme)
      ))

  (defun find-all (pattern string)
    ;; Reference: https://emacs.stackexchange.com/a/7150
    "Return a list of all regexp matches in a string."
    (reverse
     (let ((pos 0)
           matches)
       (while (string-match pattern string pos)
         (push (match-string 0 string) matches)
         (setq pos (match-end 0)))
       matches)))

  (defun minute-in-day (hour minute)
    "Get time in units of minute during a day."
    (+ (* hour 60) minute))

  ;; solar-setup
  (setq calendar-longitude (get-conf! "longitude"))
  (setq calendar-latitude (get-conf! "latitude"))

  (defun synchronize-theme ()
    "Set theme by time."
    (let ((time-str (cdr (find-all "[0-9]?[0-9]" (current-time-string))))
          (solar-str (find-all "[0-9]?[0-9]" (silent-forward! sunrise-sunset)))
          hour
          minute
          sunrise-hour
          sunrise-minute
          sunset-hour
          sunset-minute
          )
      (setq hour (string-to-number (pop time-str)))
      (setq minute (string-to-number (pop time-str)))
      (setq sunrise-hour (string-to-number (pop solar-str)))
      (setq sunrise-minute (string-to-number (pop solar-str)))
      (setq sunset-hour (+ (string-to-number (pop solar-str)) 12))
      (setq sunset-minute (string-to-number (pop solar-str)))
      (if (< (minute-in-day sunrise-hour sunrise-minute)
             (minute-in-day hour minute)
             (minute-in-day sunset-hour sunset-minute))
          (change-theme theme-light)
        (change-theme theme-dark)
        )
      ))

  (add-hook 'emacs-startup-hook
            (lambda ()
              (run-with-timer 0 60 #'synchronize-theme)))
#+end_src

*** Set theme pairs

User can set theme pairs interactively.

#+begin_src emacs-lisp
  (defun theme-set ()
    "Interactively set Emacs theme pairs."
    (interactive)
    (let ((choice (completing-read
  		 "Choose contrast level (modus/modus-tinted/tango): "
  		 '("modus" "modus-tinted" "tango") nil t)))
      (cond
       ((string= choice "modus")
        (setq theme-light 'modus-operandi)
        (setq theme-dark 'modus-vivendi))
       ((string= choice "modus-tinted")
        (setq theme-light 'modus-operandi-tinted)
        (setq theme-dark 'modus-vivendi-tinted))
       ((string= choice "tango")
        (setq theme-light 'tango)
        (setq theme-dark 'tango-dark))
       (t
        (message "Invalid choice: %s" choice)))
      (customize-save-variable 'theme-light theme-light)
      (customize-save-variable 'theme-dark theme-dark)
      (message (format "Loaded theme: %s" choice))
      (synchronize-theme)
      ))
#+end_src

** Fonts
*** Fonts for Emacs

The settings of the fonts are provided in Table [[conf-table]]. On Linux
systems, The following code do nothing if font attribute are set to
"default". On Windows systems, The default font is set to "Consolas"
with size 110, and default cjk font is "微软雅黑".

#+begin_src emacs-lisp :var conf-table=conf-table
   (let ((font (get-conf! "font"))
         (font-size (get-conf! "font-size"))
         (cjk-font (get-conf! "cjk-font"))
         (cjk-font-size (get-conf! "cjk-font-size"))
         )
     (when (eq 'windows-nt system-type)
       (if (equal font "default")
           (setq font "Consolas"))
       (if (equal font-size "default")
           (setq font-size 11))
       (if (equal cjk-font "default")
           (setq cjk-font "微软雅黑"))
       )
     (unless (equal font "default")
       (set-face-attribute 'default nil :font font)
       (set-face-attribute 'fixed-pitch nil :font font))
     (unless (equal font-size "default")
       (set-face-attribute 'default nil
                           :height (* font-size 10))
       (set-face-attribute 'fixed-pitch nil
                           :height (* font-size 10)))

   ;; Apply the setting only in a window system, as setting the
   ;; following fonts in terminal may fail.
   (if (window-system)
       (dolist (charset '(kana han cjk-misc bopomofo))
         (set-fontset-font
          (frame-parameter nil 'font)
          charset
          (font-spec
           :family (if (equal cjk-font "default")
                       nil cjk-font)
           )
          )
         )
     )
   )

  ;; Set fallback fonts for windows GUI.
  (when (and (window-system) (eq system-type 'windows-nt))
    (set-fontset-font t 'unicode "Segoe UI Symbol" nil 'append)
    (setq face-font-rescale-alist
        '(("Segoe UI Symbol" . 0.88)))
    )
#+end_src

*** All-the-icons

Need to run ~all-the-icons-install-fonts~ to install the icons.

Use ~all-the-icons-available~ to check whether ~all-the-icons~ is
available now.

#+begin_src emacs-lisp
  (use-package all-the-icons :ensure t
    :if (display-graphic-p))

  (defun all-the-icons-available ()
    "Check if all-the-icons fonts are available."
    (if (display-graphic-p)
        (find-font (font-spec :name "all-the-icons"))
      nil
      )
    )

  (when (and (not (all-the-icons-available)) (display-graphic-p))
    (message "All the icons requires installation.")
    (all-the-icons-install-fonts)
    )

#+end_src

** Window Layouts
*** Window Components
**** Menu, tools and scroll bar

I'd like to turn off menu, tool and scroll bar by default.

#+begin_src emacs-lisp
  (menu-bar-mode 0)
  (tool-bar-mode 0)
  (scroll-bar-mode 0)
#+end_src

***** Scrollbar shortcut

However, scroll bar mode can be toggled by the middle key of the
mouse.
#+begin_src emacs-lisp
  (global-set-key (kbd "<mouse-2>") 'scroll-bar-mode)
#+end_src

**** COMMENT Show line numbers

Show line numbers on the left of the window.

#+begin_src emacs-lisp
  (global-display-line-numbers-mode t)
#+end_src

*** Window split

Window split threshold. If the width of the frame is less than
140, split horizontally, else split vertically.

#+begin_src emacs-lisp
  (setq split-width-threshold 140)
#+end_src

** Troubleshooting
*** Window size issue

In X11 window, the default window size seems to be very
small. This might be a BUG, but easy to fix. The following
function also sets consistent window sizes for all systems.

#+begin_src emacs-lisp
  ;; Set window height and width.
  (setq default-frame-alist '((height . 32) (width . 80)))
#+end_src

* Editor
** Scrolling

Preserve cursor point when scrolling.

#+begin_src emacs-lisp
  (setq scroll-preserve-screen-position t)
#+end_src

Use ~ultra-scroll~ for smooth scrolling.

#+begin_src emacs-lisp
  (use-package ultra-scroll
    :ensure t
    :init
    (setq scroll-conservatively 3) ; or whatever value you prefer, since v0.4
  					;scroll-margin 0)        ; scroll-margin>0 is now supported, since v0.7
    :config
    (ultra-scroll-mode 1))
#+end_src

** Multilingual environment

*** Language coding system

Set prefered coding system to ~utf-8~. Note that
~(set-language-environment "UTF-8")~ is not used because it may ruin
some environments, such as aidermacs.

#+begin_src emacs-lisp
  ;; (set-language-environment "UTF-8")
  (prefer-coding-system 'utf-8)
#+end_src

*** Input method

Use "TeX" as default input method.

#+begin_src emacs-lisp
  (setq default-input-method "TeX")
#+end_src

** Tools
*** Dired

Use icons for dired. Requires ~all-the-icons~ to be properly installed.

#+begin_src emacs-lisp
  (when (all-the-icons-available)
   (use-package all-the-icons-dired
    :ensure t
    :hook (dired-mode . all-the-icons-dired-mode)
    )
   )
#+end_src

** Default modes
*** Built-in
**** Column number mode

Show column number on the bottom of the editor buffer.

#+begin_src emacs-lisp
  (column-number-mode 1)
#+end_src

**** Show paren mode

Show matching parentheses. This becomes default behavior since Emacs
version 28.

#+begin_src emacs-lisp
  (show-paren-mode 1)
#+end_src

**** Auto revert mode

Automatically revert buffer if its content is changed
somewhere else.

#+begin_src emacs-lisp
  (global-auto-revert-mode t)
  ;; Also revert non-file buffers such as dired.
  (setq global-auto-revert-non-file-buffers t)
#+end_src

**** Which key mode

Enable ~which-key-mode~ by default.

#+begin_src emacs-lisp
  (which-key-mode t)
#+end_src

**** COMMENT Delete selection mode

+Delete the selected region if text entered.+ Disabled.

#+begin_src emacs-lisp
  ;; (delete-selection-mode t)
#+end_src

*** Recent files

Exclude files in =~/.emacs.d/=.

#+begin_src emacs-lisp
  (add-to-list 'recentf-exclude ".emacs.d/")
#+end_src

Enable recentf mode and save recent opened files every 5 minutes.

#+begin_src emacs-lisp
  (recentf-mode t)
  (run-at-time (current-time) (* 5 60)
               (lambda () (silent-forward! recentf-save-list)))
#+end_src

*** Yasnippet

Always turn yasnippet mode on.

#+begin_src emacs-lisp
  ;; First make sure it is installed.
  (use-package yasnippet :ensure t)
  (yas-global-mode t)
#+end_src

*** COMMENT Yascroll

This is disabled because it does not work well with ~ultra-scroll~.

Use ~yascroll-mode~ for all ~text-mode~.

#+begin_src emacs-lisp
  (use-package yascroll
    :ensure t
    :config
    (add-hook 'text-mode-hook #'yascroll-bar-mode)
    )
#+end_src

*** Ivy, Swiper and Counsel

**** Basic settings

Do not enable the whole ivy mode as I just want to use a portion
of its funcitons. (to enable the whole ivy-mode, use =(ivy-mode
1)=)

#+begin_src emacs-lisp
  ;; First make sure it is installed.
  (use-package ivy :ensure t :no-require t)
  (use-package swiper :ensure t :no-require t)
  (use-package counsel :ensure t :no-require t)
  ;; ivy virtual buffer
  (setq ivy-use-virtual-buffers t)
  ;; ivy mini buffer
  (setq enable-recursive-minibuffers t)
#+end_src

**** Use icons

Use icons for ivy. Requires ~all-the-icons~ to be properly installed.

#+begin_src emacs-lisp
  (when (all-the-icons-available)
    (use-package all-the-icons-ivy-rich
    :ensure t
    :init (all-the-icons-ivy-rich-mode 1))

    (use-package ivy-rich
      :ensure t
      :init (ivy-rich-mode 1))
   )

  (setq all-the-icons-ivy-rich-color-icon nil)
#+end_src

*** Projectile

Instructions for setting up projectile is given by its [[https://github.com/bbatsov/projectile][homepage]].

**** Installation

First make sure it is installed.

#+begin_src emacs-lisp
  (use-package projectile :ensure t)
#+end_src

**** Enable Projectile and its keymap

#+begin_src emacs-lisp
  (projectile-mode t)
  ;; Recommended keymap prefix on Windows/Linux
  (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
#+end_src

**** Ivy

Basically, ~ivy-mode~ is automatically enabled for projectile if it is
activated. However, we do not enable ivy in the global scope and need
to enable it manually following [[https://docs.projectile.mx/projectile/configuration.html#completion-options][this link]].

#+begin_src emacs-lisp
  (setq projectile-completion-system 'ivy)
#+end_src

*** Marginalia

Marginalia in the minibuffer. [[https://github.com/minad/marginalia][Marginalia Homepage]].

#+begin_src emacs-lisp
  (use-package marginalia :ensure t)
  (marginalia-mode t)
#+end_src

*** Flycheck

Ensure installation of ~Flycheck~ mode.

This mode is not suggested to be activated by default using
~(global-flycheck-mode)~. It is suggested to be activated only for
~prog-mode~.

#+begin_src emacs-lisp
  (use-package flycheck :ensure t)
  ;; (global-flycheck-mode)
#+end_src

*** Rainbow

Rainbow mode by default.

#+begin_src emacs-lisp
  (use-package rainbow-mode :ensure t :no-require t)
  (add-hook 'prog-mode-hook 'rainbow-mode)
#+end_src

*** Page-break-lines

Display ugly =^L= page breaks as tidy horizontal lines.

#+begin_src emacs-lisp
  (use-package page-break-lines :ensure t)
  (global-page-break-lines-mode)
  (set-fontset-font "fontset-default"
                    (cons page-break-lines-char page-break-lines-char)
                    (face-attribute 'default :family))
#+end_src

Enable this mode in all program modes.

#+begin_src emacs-lisp
  (add-to-list 'page-break-lines-modes 'prog-mode)
#+end_src

*** Highlight indentation

#+begin_src emacs-lisp
  (use-package highlight-indentation
    :ensure t :no-require t)
#+end_src

*** COMMENT Git-gutter

Use ~diff-hl~ instead.

**** Enable git-gutter

Display file changes if a git repository is found.

#+begin_src emacs-lisp
  (use-package git-gutter :ensure t)
  (global-git-gutter-mode t)
  (custom-set-variables
   '(git-gutter:update-interval 2))	; Update every 2 seconds
#+end_src

**** Styles

#+begin_src emacs-lisp
    (custom-set-variables
   '(git-gutter:modified-sign " ")
   '(git-gutter:added-sign " ")
   '(git-gutter:deleted-sign "_"))

  (set-face-background 'git-gutter:modified "royal blue")
  (set-face-background 'git-gutter:added "forest green")
  (set-face-background 'git-gutter:deleted "salmon")
  (set-face-foreground 'git-gutter:deleted "red")
#+end_src

*** Diff-hl
**** Basic settings

Use ~diff-hl~ to compare file differences in different versions.

#+begin_src emacs-lisp
  (use-package diff-hl :ensure t
    :config
    (require 'diff-hl-dired)
    (global-diff-hl-mode t)
    (add-hook 'after-save-hook 'diff-hl-update)
    (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh) ; Refresh after magit operations
    (diff-hl-flydiff-mode t)		; Refresh on the fly
    (setq diff-hl-flydiff-delay 4)	; Avoid lag from constant diff updates
    )
#+end_src

**** Styles

#+begin_src emacs-lisp
  (custom-set-faces
   '(diff-hl-insert  ((t (:background "forest green" :foreground "white"))))
   '(diff-hl-change  ((t (:background "royal blue" :foreground "white"))))
   '(diff-hl-delete  ((t (:background "orange red" :foreground "white")))))

  (setq diff-hl-margin-symbols-alist
        '((insert . "+") (delete . "-") (change . "~")
  	(unknown . "?") (ignored . "i") (reference . " ")))
#+end_src

**** Dired mode

Setup ~diff-hl-dired-mode~.

#+begin_src emacs-lisp
  (add-hook 'dired-mode-hook 'diff-hl-dired-mode)
  (add-hook 'dired-mode-hook 'diff-hl-dired-mode-unless-remote)
  (add-hook 'magit-post-refresh-hook 'diff-hl-dired-update)
#+end_src

** Functions and key bindings
*** Upcase and downcase region

Upcase and downcase region.

#+begin_src emacs-lisp
  ;; C-x C-u
  (put 'upcase-region 'disabled nil)
  ;; C-x C-l
  (put 'downcase-region 'disabled nil)
#+end_src

*** Ivy, Counsel and Swiper

Key bindings for counsel. I just enable some of the key bindings
here.

#+begin_src emacs-lisp
  (global-set-key (kbd "C-s") 'swiper)
  (global-set-key (kbd "M-x") 'counsel-M-x)
  (global-set-key (kbd "C-x b") 'counsel-switch-buffer)
  (global-set-key (kbd "C-x B") 'counsel-switch-buffer-other-window)
  (global-set-key (kbd "C-x C-f") 'counsel-find-file)
  (global-set-key (kbd "C-x C-y") 'counsel-yank-pop)
  ;;(define-key ivy-minibuffer-map (kbd "C-j") 'ivy-immediate-done)
#+end_src

*** Mwim

Move to the beginning/end of line, code or comment in a
better (?)  way. It should be mentioned that =M-m= is a
built-in shourtcut for navigating to the first
non-whitespace character on this line, which I think is
idential to =mwim-beginning-of-code=.

#+begin_src emacs-lisp
  (use-package mwim :ensure t :no-require t)
  (autoload 'mwim-beginning-of-code "mwim" nil t)
  (autoload 'mwim-end-of-code "mwim" nil t)
  (global-set-key (kbd "M-g a") 'mwim-beginning-of-code)
  (global-set-key (kbd "M-g e") 'mwim-end-of-code)
  ;; (global-set-key (kbd "<home>") 'mwim-beginning-of-line-or-code)
  ;; (global-set-key (kbd "<end>") 'mwim-end-of-line-or-code)
#+end_src

*** Avy

Jump to text using a char-based decision tree. It's really
cool!

#+begin_src emacs-lisp
  (use-package avy :ensure t :no-require t)
  (global-set-key (kbd "C-;") 'avy-goto-char)
  (global-set-key (kbd "C-'") 'avy-goto-line)
  (global-set-key (kbd "M-g l") 'avy-goto-line)
  (global-set-key (kbd "M-g w") 'avy-goto-word-1)
  (global-set-key (kbd "M-g k") 'avy-kill-region)
  (global-set-key (kbd "M-g y") 'avy-copy-region)  ; yank
  (global-set-key (kbd "M-g t") 'avy-move-region)  ; teleport
#+end_src

*** Ace window

Bind =M-o= to use ace-window.

#+begin_src emacs-lisp
  (use-package ace-window :ensure t :no-require t)
  (global-set-key (kbd "M-o") 'ace-window)
#+end_src

*** Multiple cursors

[[https://github.com/magnars/multiple-cursors.el][Multiple cursors]] for Emacs.

#+begin_src emacs-lisp
  (use-package multiple-cursors :ensure t :no-require t)
  (global-set-key (kbd "C->") 'mc/mark-next-like-this)
  (global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
  (global-set-key (kbd "C-?") 'mc/mark-all-dwim)
  (global-set-key (kbd "C-S-<mouse-1>") 'mc/toggle-cursor-on-click)
#+end_src

*** Hide lines

Hide lines using regexp.

#+begin_src emacs-lisp
  (use-package hide-lines :ensure t)
#+end_src

*** My own functions
**** Open new line

Open a new line below or above the current one by using
=S-<enter>= and =C-S-<enter>=.

#+begin_src emacs-lisp
  (defun open-and-indent-line-below (&optional n)
    "Insert a newline below and indent and leave point after it.
  With arg N, insert and indent N newlines."
    (interactive "*p")
    (when (< (prefix-numeric-value n) 0)
      (error "Repetition argument has to be non-negative"))
    (beginning-of-line)
    (skip-syntax-forward " " (line-end-position))
    (let ((indent (current-column)))
      (end-of-line)
      (dotimes (i n)
        (newline)
        (indent-to indent)
        )
      (forward-line (- 1 n))
      (end-of-line)
      )
    )

  (defun open-and-indent-line-above (&optional n)
    "Insert a newline above and indent and leave point after it.
  With arg N, insert and indent N newlines."
    (interactive "*p")
    (when (< (prefix-numeric-value n) 0)
      (error "Repetition argument has to be non-negative"))
    (beginning-of-line)
    (skip-syntax-forward " " (line-end-position))
    (let ((indent (current-column)))
      (dotimes (i n)
        (beginning-of-line)
        (open-line 1)
        (indent-to indent)
        )
      (end-of-line)
      )
    )

  (global-set-key (kbd "S-<return>")
                  'open-and-indent-line-below)
  (global-set-key (kbd "C-S-<return>")
                  'open-and-indent-line-above)
#+end_src

**** Reversed yank

Yank the previous kill. This is equivalent to =M-- M-y=.

#+begin_src emacs-lisp
    (defun yank-pop-reversed (&optional arg)
      "Replace the just-yanked stretch with a more recent kill.
    This is the reverse of builtin-function `yank-pop`, which
    replaces the previous yanked text with a more recent kill by
    default."
      (interactive "*p")
      (unless arg (setq arg 1))
      (yank-pop (- arg)))

    (global-set-key "\C-\M-Y" 'yank-pop-reversed)
#+end_src

** Mode line format
*** Mode line format

Define the mode-line style.

Please make sure ~all-the-icons~ is properly installed first to enable
icon display.

**** Syntax checker mode line

Use flycheck for syntax checking and display the result in the mode
line.

#+begin_src emacs-lisp
  (if (all-the-icons-available)
      (progn
        (setq flycheck-warning-icon
  	    (all-the-icons-faicon "exclamation-triangle"
  				  :face 'warning :height 0.8 :v-adjust 0.0))
        (setq flycheck-error-icon
  	    (all-the-icons-faicon "times-circle"
  				  :face 'error :height 0.8 :v-adjust 0.0))
        (setq flycheck-check-passed-icon
  	    (all-the-icons-faicon "check-circle"
  				  :height 0.8 :v-adjust 0.0))
        (setq flycheck-checking-icon
  	    (all-the-icons-faicon "spinner"
  				  :height 0.8 :v-adjust 0.0))
        (setq flycheck-suspicious-icon
  	    (all-the-icons-faicon "question"
  				  :height 0.8 :v-adjust 0.0))
        (setq flycheck-exclamation-icon
  	    (all-the-icons-faicon "exclamation"
  				  :height 0.8 :v-adjust 0.0))
        (setq flycheck-no-checker-icon
  	    (all-the-icons-faicon "minus-circle"
  				  :height 0.8 :v-adjust 0.0))
        (setq flycheck-not-checked-icon
  	    (all-the-icons-faicon "minus-circle"
  				  :face 'shadow :height 0.8 :v-adjust 0.0))
        (setq flycheck-interrupted-icon
  	    (all-the-icons-faicon "circle-o"
  				  :height 0.8 :v-adjust 0.0))
        )
    (setq flycheck-warning-icon (propertize "!" 'face 'warning))
    (setq flycheck-error-icon (propertize "×" 'face 'error))
    (setq flycheck-check-passed-icon "√")
    (setq flycheck-checking-icon "...")
    (setq flycheck-suspicious-icon "?")
    (setq flycheck-exclamation-icon "!")
    (setq flycheck-no-checker-icon "-")
    (setq flycheck-not-checked-icon (propertize "-" 'face 'shadow))
    (setq flycheck-interrupted-icon "o")
    )

  (defun flycheck-popup-menu ()
    "The popup window for flycheck in mode-line."
    (interactive)
    (let ((menu
           (list "Syntax checking"
                 (vector "Turn on/off syntax checker"
                         #'flycheck-mode
                         )
  	       "--"
                 (vector "Check current buffer"
                         #'flycheck-buffer
                         (not (not (and flycheck-mode
  				      (flycheck-get-checker-for-buffer)))))
  	       "--"
                 (vector "Go to previous error"
                         #'flycheck-previous-error
                         (flycheck-has-current-errors-p))
                 (vector "Go to next error"
                         #'flycheck-next-error
                         (flycheck-has-current-errors-p))
                 (vector "Show all errors"
                         #'flycheck-list-errors
                         (flycheck-has-current-errors-p))
                 (vector "Explain error at point"
                         #'flycheck-explain-error-at-point
                         (flycheck-has-current-errors-p))
  	       )))
      (popup-menu menu)))

  (defun get-flycheck-mode-line-with-icon ()
    "Display the flycheck status."
    (let* ((current-status flycheck-last-status-change)
           (indicator
  	  (pcase current-status
              (`not-checked flycheck-not-checked-icon)
              (`no-checker flycheck-no-checker-icon)
              (`running flycheck-checking-icon)
              (`errored flycheck-exclamation-icon)
              (`finished
               (let-alist (flycheck-count-errors flycheck-current-errors)
  	       (if (and .error .warning)
  		   (format "%s%s %s%s"
  			   flycheck-error-icon .error
  			   flycheck-warning-icon .warning)
  		 (if .error
  		     (format "%s%s" flycheck-error-icon .error)
  		   (if .warning
  		       (format "%s%s" flycheck-warning-icon .warning)
  		     flycheck-check-passed-icon
  		     )))))
              (`interrupted flycheck-interrupted-icon)
              (`suspicious flycheck-suspicious-icon)))
  	 (status-message
  	  (pcase current-status
  	    (`not-checked "not checked")
  	    (`no-checker "no checker")
  	    (`running "checking")
  	    (`errored "checker error")
  	    (`finished
  	     (let-alist (flycheck-count-errors flycheck-current-errors)
  	       (format "finished - errors: %s, warnings: %s"
  		       (or .error 0) (or .warning 0))))
  	    (`interrupted "interrupted")
  	    (`suspicious "suspicious")))
           (text (format "%3s" indicator))
  	 (map (let ((m (make-sparse-keymap)))
                  (define-key m [mode-line mouse-1] #'flycheck-popup-menu)
                  m)))
      (propertize text
                  'mouse-face 'mode-line-highlight
                  'help-echo (concat "Syntax checking status\n"
  				   status-message
  				   "\n"
  				   "mouse-1: Syntax checker menu"
  				   )
  		'local-map map
  		)))
#+end_src

**** Project mode line

Set project mode display function in mode line.

#+begin_src emacs-lisp
  (setq project-mode-icon
        (if (all-the-icons-available)
  	  (concat (all-the-icons-octicon
  		   "repo"
  		   :face '(:height 0.9 :family "github-octicons")
  		   :v-adjust 0.02)
  		  " ")
  	"Proj:"))

  (defun get-project-mode-with-icon ()
    "Return Project mode string with icon and perserved properties"
    (let ((proj-str-orig (project-mode-line-format)))
    (when proj-str-orig
      (let* ((proj-str (replace-regexp-in-string "^ " "" proj-str-orig))
  	   (map (get-text-property 1 'local-map proj-str))
             (mouse (get-text-property 1 'mouse-face proj-str))
  	   (echo (get-text-property 1 'help-echo proj-str))
             (icon (propertize
  		  project-mode-icon
                    'local-map map
                    'mouse-face mouse
  		  'help-echo echo))
             )
        (concat " " icon proj-str))))
    )
#+end_src

**** Version control mode line

Set version control display function in mode line.

Currently, using git icon to replace vc-mode display.

#+begin_src emacs-lisp
  (setq vc-mode-git-icon
        (if (all-the-icons-available)
  	  (concat (all-the-icons-octicon
  		   "git-branch"
                     :face '(:height 0.95 :family "github-octicons")
                     :v-adjust 0.02)
  		  " ")
  		    "Git:"))

  (defun get-vc-mode-with-icon ()
    "Return VC mode string with icon and perserved properties"
    (when vc-mode
      (let* ((map (get-text-property 1 'local-map vc-mode))
             (mouse (get-text-property 1 'mouse-face vc-mode))
  	   (echo (get-text-property 1 'help-echo vc-mode))
             (icon (propertize
  		  vc-mode-git-icon
                    'local-map map
                    'mouse-face mouse
  		  'help-echo echo)
  		 )
             (branch (replace-regexp-in-string "^ Git[:\\-\\@]" "" vc-mode)))
        (concat " " icon branch)))
    )
#+end_src

**** Mode line content

Set mode line format.

#+begin_src emacs-lisp
  (setq-default mode-line-format
  '("%e" mode-line-front-space
   (:propertize
    ("" mode-line-mule-info mode-line-client mode-line-modified
     mode-line-remote mode-line-window-dedicated)
    display (min-width (5.0)))
   mode-line-frame-identification mode-line-buffer-identification "  "

   mode-line-position

   ;; Add information for syntax checking.
   (:eval (get-flycheck-mode-line-with-icon)) " "

   ;; The default values for the next block are:
   ;;(project-mode-line project-mode-line-format)
   ;; (vc-mode vc-mode)
   ;; I want these to be evaluated online, to avoid out-of-dated version
   ;; display.
   (:eval (get-vc-mode-with-icon))
   (:eval (get-project-mode-with-icon))
   ;;

   "  " mode-line-modes mode-line-misc-info
   mode-line-end-spaces)
  )
#+end_src

*** Hide all minor modes
#+begin_src emacs-lisp
  (use-package minions
    :ensure t
    :config
    (setq minions-prominent-modes '())
    (setq minions-mode-line-lighter
  	(if (char-displayable-p ?☰) "☰" "Modes"))
    (minions-mode 1)
    )
#+end_src

** Backup setting

Set the Backup directory. Different Directories are used for
Linux and Windows by default. The directory can be modified
by =conf-table=.

#+begin_src emacs-lisp :var conf-table=conf-table
  (let ((dir (get-conf! "backup-dir")))
    (if (equal dir "default")
        (progn
          (if (eq 'gnu/linux system-type)
              (setq dir "~/.emacs_backups/")
            )
          (if (eq 'windows-nt system-type)
              (setq dir "C:/cache/.emacs_backups/")
            )
          ))
    (setq backup-directory-alist `(("." . ,dir)))
    )
#+end_src

** Troubleshooting

In X11, <delete> works as backward delete, which should be forward
delete. I don't know whether it is a bug. But it is easy to work
around this issue.

#+begin_src emacs-lisp
  ;; Note that operating-system-release might be nil on windows,
  ;; which can not be argument of string-match-p.
  (if operating-system-release
      (if (string-match-p
           "microsoft-standard-WSL"
           operating-system-release)
          (global-set-key (kbd "<delete>") 'delete-forward-char)
        )
    )
#+end_src

* Major modes
** Org Mode
*** Basic setting

Start org-mode with all headers collapsed. The default
setting of Emacs minght be different on different
machines. So we set it here.

#+begin_src emacs-lisp
  (setq org-startup-folded t)
#+end_src

Wrap long lines in Org mode.

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook (lambda () (setq truncate-lines nil)))
#+end_src

Enable shift-select.

#+begin_src emacs-lisp
  (setq org-support-shift-select t)
#+end_src

Use Org-indent-mode. This mode also hides leading start in
org-mode by locally setting =org-hide-leading-stars= to =t=.
See [[https://orgmode.org/manual/Org-Indent-Mode.html][org mode manual]] for more details.

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)
#+end_src

*** Constants

#+begin_src emacs-lisp
  (setq org-table-formula-constants
        '(("π" . "3.14159265359")
          ("pi" . "3.14159265359")
          ("e" . "2.718281828459")
          ))
#+end_src

*** Apperance setting
**** Character display

Use utf-8 characters for display. Use "C-c C-x \" to toggle.

#+begin_src emacs-lisp
  (setq org-pretty-entities t)
#+end_src

Hide *, ~ and / in org text.

#+begin_src emacs-lisp
  (setq org-hide-emphasis-markers t)
#+end_src

**** COMMENT Hide leading stars

+Hide the verbose leading stars before headlines.+
This feature is automatically enabled by =org-indent-mode=.

#+begin_src emacs-lisp
  (setq org-hide-leading-stars t)
#+end_src

**** Org superstar

Use Org superstar mode.

#+begin_src emacs-lisp
(use-package org-superstar :ensure t :no-require t)
(add-hook 'org-mode-hook (lambda () (org-superstar-mode 1)))
#+end_src

**** Org ellipsis style

I'd like something fancy instead of the ellipsis (...) that org
displays when there's staff under a header. The arrow symbol is
found from [[https://unicode-table.com/en/sets/arrow-symbols/][Unicode Character Table]].

This feature will only be enabled if the desired character is
displayable in the current environment.

#+begin_src emacs-lisp
  ;; I'd like to use a fancy symbol, such as "..⤸" for folded code. However,
  ;; org-ellipsis font fails to fallback when fringe display is enableb.
  ;; (e.g., diff-hl-mode).
  ;; (if (char-displayable-p ?⤸)
  ;;     (setq org-ellipsis "..⤸")
  ;;   (setq org-ellipsis "...")
  ;;   )

  (if (char-displayable-p ?·) ; `·` should be in most fonts
      (setq org-ellipsis " <···> ")
    (setq org-ellipsis " <...> ")
    )
  (set-face-underline 'org-ellipsis nil)
  (set-face-bold 'org-ellipsis t)
#+end_src

*** "TODO" list setting

Org mode keyword settings.

#+begin_src emacs-lisp
  (setq org-todo-keywords
        '((sequence "TODO(t)" "DOING(i)"
                    "|"
                    "DONE(d)" "ABORT(a)" "POSTPONED(p)")))
  (setq org-todo-keyword-faces
        '(("TODO" . "red")
          ("DOING" . "orange")
          ("DONE" . "dark cyan")
          ("ABORT" . "dim grey")
          ("POSTPONED" . "dark magenta")))
#+end_src

*** Source code block setting
**** Source code window setting

Use the current window for editing source blocks (Press C-c ' in
source code block).

#+begin_src emacs-lisp
  (setq org-src-window-setup 'current-window)
#+end_src

**** Babel enable languages

Enable Python, C, C++ and D languages.

#+begin_src emacs-lisp
  ;; Enable shell command.
  (org-babel-do-load-languages 'org-babel-load-languages
                               '((shell . t)))
  ;; Enable Python.
  (org-babel-do-load-languages 'org-babel-load-languages
                               '((python . t)))
  ;; Enable C, C++ and D.
  (org-babel-do-load-languages 'org-babel-load-languages
                               '((C . t)))
  ;; Enable latex.
  (org-babel-do-load-languages 'org-babel-load-languages
                               '((latex . t)))
#+end_src

Run these codes without prompting.

#+begin_src emacs-lisp
  (defun my-org-confirm-babel-evaluate (lang body)
    (not (member lang '("C" "C++" "python" "emacs-lisp")))
    )
  (setq org-confirm-babel-evaluate 'my-org-confirm-babel-evaluate)
#+end_src

**** Python setting for babel

Switch python backend setted in configuration table for babel python
mode.

Note that as matplotlib do not work well in emacs on windows machines,
the interpreter is set to ~ipython~ by default. See troubleshooting
in python mode settings.

#+begin_src emacs-lisp :var conf-table=conf-table
  ;; Use string= for string comparasion!
  ;; (eq "str" "str") returns nil.
  (let ((interpreter (get-conf! "python-interpreter")))
    (if (string= interpreter "default")
        (if (eq 'windows-nt system-type)
            (setq org-babel-python-command "ipython")
           )
        ;; Org babel mode.
        (setq org-babel-python-command interpreter))
  )
#+end_src

*** Export

Do not re-execute the source code blocks during export.

#+begin_src emacs-lisp
  (setq org-export-babel-evaluate nil)
#+end_src

*** Keybindings
**** Toggle blocks
Use ~C-<tab>~ for toggle hiding of the buffer, ~C-~`~ for toggle the
current block. This is to achieve consistent experience with
~hs-toggle-buffer~ and ~hs-toggle-hidding~ function.

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook
            (lambda ()
              (define-key org-mode-map (kbd "C-<tab>") #'org-cycle-global)
              (define-key org-mode-map (kbd "C-`") #'org-cycle)
  	    ))
#+end_src

*** Troubleshooting
**** COMMENT Indentation

The source code block should presrve the source code's
indentation. That is, leave the whitespaces as it instead of
converting them to tabs. However, after editing the source code
block using =C-c '=, the source code block will be indented
automatically, and converts spaces to tabs. To disable this
behaviour, one solution is to disable the source code block from
automatically indent the codes. The following code works by
cancelling all indents of source code blocks: ~(setq
org-src-preserve-indentation nil)~. However, this is not what we
want as we need an organized structure which indents
correctly. Another workaround is to disable the =indent-tab-mode= in
=org-mode=, which forces =org-mode= to use spaces for indentation. The
drawback of this solution is all leading tabs will become
whitespaces. And to insert tab in =org-mode=, press =C-q tab=.

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook
  (lambda () (setq indent-tabs-mode nil)))
#+end_src

**** Page-breaklines mode compability

Disable page-breaklines mode because it does not work with
org-indent-mode.

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook (lambda () (page-break-lines-mode -1)))
#+end_src

**** Hiding leading stars

The leading stars of the titles in =org-mode= are hided by
setting =org-hide-leading-starts= to =t=. This feature is
implemented by setting the font of leading starts to
=org-hide=, which has the same color as the
background. However, this color doesn't change when the
background color changes. Thus, the leading stars will show
in a different color when the theme changes.

The [[https://github.com/integral-dw/org-superstar-mode][homepage]] of =org-superstar-mode= gives a solution, which
solves the problem when =org-indent-mode= is disabled.

#+begin_src emacs-lisp
  ;; This is usually the default, but keep in mind it must be nil
  (setq org-hide-leading-stars nil)
  ;; This line is necessary.
  (setq org-superstar-leading-bullet ?\s)
  ;; If you use Org Indent you also need to add this, otherwise the
  ;; above has no effect while Indent is enabled.
  (setq org-indent-mode-turns-on-hiding-stars nil)
#+end_src

To hide the leading stars inserted by =org-indent-mode=, we
can set the foreground color of the leading stars to the
same as the background. We can automatically run this procedure
by function =advice-add= (see [[https://emacs.stackexchange.com/a/41250/38157][this stackexchange answer]]).

#+begin_src emacs-lisp
  (defun hide-org-indent-leading-stars (&optional theme)
    "Hide the leading stars generated by org-indent mode."
    (when (member 'org-indent (face-list))
    (set-face-attribute 'org-indent nil
                        :foreground (face-attribute 'default :background))
    ))
  (advice-add 'enable-theme :after #'hide-org-indent-leading-stars)
  (advice-add 'disable-theme :after #'hide-org-indent-leading-stars)
#+end_src

** Prog Mode

In Emacs, =prog-mode= is the base mode for programming.

*** Minor mode settings
**** Company mode

Use Company mode for auto-completion.

Please note ~company-mode~ in ~python-shell~ would lead to undefined behavior for ~input()~ function in ~python~. Only activate this mode for ~prog-mode~.

#+begin_src emacs-lisp
  ;; First make sure it is installed.
  (use-package company :ensure t)
  (add-hook 'prog-mode-hook #'company-mode)
#+end_src

**** Hs minor mode
***** Enabler

Enable ~hs-minor-mode~ for all prog modes.

#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook #'hs-minor-mode)
#+end_src
***** Overlay style

Show different fonts for overlay.

#+begin_src emacs-lisp
  (defun hs-display-overlay (ov)
    "Display custom indicator for hidden code indicated by OV."
      (let* ((ellipsis (if (char-displayable-p ?·) "···" "..."))
  	   (nlines (count-lines (overlay-start ov) (overlay-end ov)))
             (info (propertize (format " %s " ellipsis)
  			     'face
  			     'org-ellipsis)))
        (overlay-put ov 'display info)))

  (setq hs-set-up-overlay #'hs-display-overlay)
#+end_src

***** Toggle hidding shortcut

Use ~C-`~ for toggle hiding.

#+begin_src emacs-lisp
  (with-eval-after-load 'hideshow
      (define-key hs-minor-mode-map (kbd "C-`") #'hs-toggle-hiding))
#+end_src

***** Code folding shortcut

*This block will be deprecated after Emacs 31. Use ~hs-cycle~ instead.*

Use ~S-<tab>~ for Org-style folding.

#+begin_src emacs-lisp
  (defvar-local hs-toggle-state 'hide-all "Record block hide-show status.")

  (defun hs-toggle-buffer ()
    "Toggle Hide-show status in the current buffer.
  The status will switch between `hide-all`, `show-all`."
    (interactive)
    (unless (eq last-command 'hs-toggle-buffer)
      (setq hs-toggle-state 'hide-all)
      )
    (cond
     ((eq hs-toggle-state 'hide-all)
      (hs-hide-all)
      (setq hs-toggle-state 'show-all))
     ((eq hs-toggle-state 'show-all)
      (hs-show-all)
      (setq hs-toggle-state 'hide-all))
     )
    )

  (add-hook 'prog-mode-hook
            (lambda () (local-set-key
                        (kbd "C-<tab>")
                        'hs-toggle-buffer)))
#+end_src

**** Lsp
***** Installation

Enable Lsp mode.

#+begin_src emacs-lisp
  (use-package lsp-mode :ensure t :no-require t
    ;; :hook (prog-mode . lsp-deferred)
    )
#+end_src

***** Highlight text

Set the font of the highlight text where cursor points to.

#+begin_src emacs-lisp
  (with-eval-after-load 'lsp-mode
    (set-face-attribute 'lsp-face-highlight-textual nil
                        :inherit nil :underline t :bold t)
    (set-face-attribute 'lsp-face-highlight-read nil
                        :inherit nil :underline t :bold t)
    (set-face-attribute 'lsp-face-highlight-write nil
                        :inherit nil :underline t :bold t)
    )
#+end_src

***** Auto guess root

Automatically guess the project root using projectile/project. Do not
use this setting unless you are familiar with ~lsp-mode~ internals and
you are sure that all of your projects are following
~projectile/project.el~ conventions.

Refer to [[https://emacs-lsp.github.io/lsp-mode/page/settings/mode/#lsp-auto-guess-root][this link]] for more details.

#+begin_src emacs-lisp
  (setq lsp-auto-guess-root t)
#+end_src

***** Disable signature help documentation

Signature documentation sometimes makes the minibuffer too big when
coding. The [[https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/][official website]] gives instructions for turning off such
features.

#+begin_src emacs-lisp
  (setq lsp-signature-render-documentation nil)
#+end_src

***** Use insert instead of replace when completion

The default behaviour of lsp completion replaces the word inplace, as
described by [[https://stackoverflow.com/questions/76211988/stop-company-complete-selection-from-eating-following-word-in-rust-code][this question]]. This behavior is controlled by
~lsp-completion-default-behaviour~ in [[https://emacs-lsp.github.io/lsp-mode/page/settings/mode/#lsp-completion-default-behaviour][this link]], we can change it from
~:replace~ to ~:insert~ to solve the problem.

#+begin_src emacs-lisp
(setq lsp-completion-default-behaviour :insert)
#+end_src

***** Mode line
****** Diagnostics message

Use ~flycheck~ to show the diagnostic messages instead of ~lsp~'s native
one.

#+begin_src emacs-lisp
  (setq lsp-modeline-diagnostics-enable nil)
#+end_src

****** Code action icon

The original icon 💡 cannot be displayed properly on some
systems. Replace it with other symbol.

#+begin_src emacs-lisp
  ;; Do not use the light-bulb icon provided by lsp as the default one
  ;; is too large.
  (setq lsp-modeline-code-action-icons-enable nil)

  (setq lsp-modeline-code-actions-segments '(icon))
  (setq lsp-modeline-code-action-fallback-icon
        (if (char-displayable-p ?✨) "✨" "Hints"))

  ;; Clear lsp-modeline-code-actions-face.
  (with-eval-after-load 'lsp-mode
    (custom-set-faces
     '(lsp-modeline-code-actions-face
       ((t)))))
#+end_src

****** Lsp progress prefix

Set icon for lsp-progress displayed in mode-line, which was originally
using utf-8 char ~⌛~, and may not be properly displayed on some
platforms.

#+begin_src emacs-lisp
  (if (all-the-icons-available)
      (setq lsp-progress-prefix
  	  (all-the-icons-faicon "hourglass-half"
  				:face '(:height 0.8 :family "FontAwesome")
                                  :v-adjust 0.02))
    (if (char-displayable-p ?⌛)
        (setq lsp-progress-prefix "⌛")
      (setq lsp-progress-prefix "")
      )
    )
#+end_src

***** Headerline

****** Turn off lsp headerline by default

#+begin_src emacs-lisp
  (setq lsp-headerline-breadcrumb-enable nil)
#+end_src

****** Lsp headerline arror

Set icons for lsp headerline arrow. These is to avoid unproper display
of ">" sign on some platforms.

#+begin_src emacs-lisp
  (unless (all-the-icons-available)
    (setq lsp-headerline-arrow " >")
    )
#+end_src

**** Lsp-ui

Use ~lsp-ui~, which is an add-in package of ~lsp~.

#+begin_src emacs-lisp
  (use-package lsp-ui :ensure t
    :hook (lsp-mode . lsp-ui-mode)
    :custom
    (lsp-ui-doc-enable nil)
    (lsp-ui-sideline-enable nil)
    (lsp-ui-sideline-show-diagnostics t)
    (lsp-ui-sideline-show-code-actions t)
    :config
    (define-key lsp-ui-mode-map [remap xref-find-definitions] #'lsp-ui-peek-find-definitions)
    (define-key lsp-ui-mode-map [remap xref-find-references] #'lsp-ui-peek-find-references)
    )

#+end_src

**** Dap

Use Dap-mode for debugging. This mode is relient on ~lsp-mode~. See
[[https://emacs-lsp.github.io/dap-mode/page/configuration/][official website]] for more settings.

#+begin_src emacs-lisp
  (use-package dap-mode :ensure t :no-require t)

  ;; Enabling only some features
  (setq dap-auto-configure-features '(sessions locals controls tooltip))

#+end_src

**** Flycheck

Enable ~flycheck~ for all prog modes.

#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook #'hs-minor-mode)
#+end_src

*** Keybindings
**** Hungry delete

Use hungry delete from c-mode by using prefix "C-c".

#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook
            (lambda () (local-set-key
                        (kbd "C-c <backspace>")
                        'c-hungry-delete-backwards)))
  (add-hook 'prog-mode-hook
            (lambda () (local-set-key
                        (kbd "C-c <delete>")
                        'c-hungry-delete-forward)))
#+end_src

** Lisp mode
*** Minor mode settings
**** Rainbow delimiters mode

Use rainbow-delimiters for lisp-like languages.

#+begin_src emacs-lisp
  (use-package rainbow-delimiters :ensure t :no-require t)
  (add-hook 'lisp-mode-hook 'rainbow-delimiters-mode)
  (add-hook 'emacs-lisp-mode-hook 'rainbow-delimiters-mode)
  (add-hook 'scheme-mode-hook 'rainbow-delimiters-mode)
  ;; The effect of rainbow delimiters is as follows:
  '(((((((((.)))))))))
#+end_src

*** Functions and key bindings
**** My own funcitons
***** Run region or buffer

Use ~C-c C-c~ to eval region or buffer, depending on whether the
selected region is active.

#+begin_src emacs-lisp
  (defun eval-region-or-buffer ()
    "Evaluate the region if it is active, else eval the buffer."
    (interactive)
    (message "Evaluating region or buffer...")
    (if (and transient-mark-mode mark-active)
        (eval-region (region-beginning) (region-end))
      (eval-buffer))
    )

  (add-hook 'emacs-lisp-mode-hook
            (lambda () (local-set-key (kbd "\C-c\C-c")
                                      'eval-region-or-buffer)))
#+end_src

Press ~<f5>~ to save all buffers and run the region or buffer.

#+begin_src emacs-lisp
  (defun save-and-eval-region-or-buffer () (interactive)
         "Save all buffers, kill current python buffer and run
    current buffer or selection."
         (save-some-buffers '(4))
         (eval-region-or-buffer))
  (add-hook 'emacs-lisp-mode-hook
            (lambda () (local-set-key
                        (kbd "<f5>")
                        'save-and-eval-region-or-buffer)))
#+end_src

** Python mode
*** Basic settings
**** Python interpreter setting
***** Default setting

Switch python backend given in configuration table.

Note that as matplotlib do not work well in emacs on windows machines,
the interpreter is set to ~ipython~ by default. See troubleshooting
chapter.

#+begin_src emacs-lisp :var conf-table=conf-table
  ;; Use string= for string comparasion!
  ;; (eq "str" "str") returns nil.
  (let ((interpreter (get-conf! "python-interpreter")))
    (if (string= interpreter "default")
        (if (eq 'windows-nt system-type)
            (setq python-shell-interpreter "ipython")
         )
        (setq python-shell-interpreter interpreter))
  )
#+end_src

***** User defined interpreter

Set python interpreter interactively.

#+begin_src emacs-lisp
  (defun python-shell-set-interpreter ()
    "Set the python interpreter for the current buffer."
    (interactive)
    (setq-local python-shell-interpreter
  	      (read-string "Python interpreter: "
  			   python-shell-interpreter)))
#+end_src

**** Echo input in inferior python mode

The default python shell do not echo the input from python buffer by
calling ~python-shell-send-string~ and etc., which may cause some
confusion to the users. Here a function is provided to let the shell
display the code which is being executed.

***** Python shell output string

The code in this block is inspired by code from ~elpy-shell.el~.

#+begin_src emacs-lisp
  (defun python-shell-insert-and-font-lock (string face)
    "Inject STRING into the Python shell buffer."
    (let ((from-point (point)))
      (insert string)
      (add-text-properties from-point (point)
  			 (list 'front-sticky t 'font-lock-face face))))

  (defun python-shell-append-to-shell-output (string &optional prepend-cont-prompt)
    "Append the given STRING to the output of the Python shell buffer.

  Unless NO-FONT-LOCK is set, formats STRING as shell input.
  Prepends a continuation promt if PREPEND-CONT-PROMPT is set."
    (unless (string-empty-p string)
    (let* ((process (python-shell-get-process))
           (process-buf (python-shell-get-buffer))
           (mark-point (process-mark process)))
      (with-current-buffer process-buf
        (save-excursion
          (goto-char mark-point)
          (if prepend-cont-prompt
              (let* ((column (+ (- (point)
                                   (let ((inhibit-field-text-motion t))
                                     (forward-line -1)
                                     (end-of-line)
                                     (point)))
                                1))
                     (prompt (concat (make-string (max 0 (- column 6)) ? ) "... "))
                     (lines (split-string string "\n")))
                (goto-char mark-point)
                (python-shell-insert-and-font-lock
                 (car lines) 'comint-highlight-input)
                (when (cdr lines)
                    ;; no additional newline at end for multiline
                    (dolist (line (cdr lines))
                      (insert "\n")
                      (let ((from-point (point)))
                        (python-shell-insert-and-font-lock
                         prompt 'comint-highlight-prompt)
                        (add-text-properties
                         from-point (point)
                         '(field output inhibit-line-move-field-capture t
                                 rear-nonsticky t)))
                      (python-shell-insert-and-font-lock
                       line 'comint-highlight-input)))
                  ;; but put one for single line
                  (insert "\n"))
            (python-shell-insert-and-font-lock
             string 'comint-highlight-input))
          (set-marker (process-mark process) (point)))))))

#+end_src

***** Run python with shell echo

Run python with echo in the python shell.

#+begin_src emacs-lisp
  (defun python-shell-send-region-with-echo (start end &optional msg no-cookie)
    "Send the region delimited by START and END to Python process with shell
  echo output."
      (python-shell-append-to-shell-output (buffer-substring start end) t)
      (python-shell-send-region start end t msg no-cookie)
  )

  (defun python-shell-send-buffer-with-echo (buffer-name &optional send-main msg)
    "Send the current buffer to Python process with shell echoing running
  BUFFER-NAME."
    (python-shell-append-to-shell-output
     (if send-main
         (format "<running \"%s\">" buffer-name)
         (format "<running \"%s\" without main block>" buffer-name)
       ))
      (python-shell-send-buffer send-main msg)
  )
#+end_src

*** Minor mode settings

Choose between either elpy or lsp. Since the developement of elpy is
not active now, lsp-mode is used by default.

**** Hs minor mode
***** Org-style folding

Use ~S-<tab>~ for Org-style folding.

#+begin_src emacs-lisp
  (defvar-local hs-toggle-state 'hide-all
    "Record python block hide-show status.")

  (defun python-hs-outline ()
    "Only show function and class declarations in Python (hide their bodies)."
    (interactive)
    (hs-show-all)
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward "^\\s-*\\(def\\|class\\)\\s-+" nil t)
        (let ((ppss (syntax-ppss)))
          ;; Rule out `def/class` in docstrings.
          (unless (nth 4 ppss)
            (beginning-of-line)
            (hs-hide-block)
            (forward-line 1)))))
    (message "Show Python outline"))

  (defun python-hs-all ()
    "Show everything in Python buffer."
    (interactive)
    (hs-show-all)
    (message "Show all blocks")
    )

  (defun python-hs-top-level ()
    "Show only top-level Python function and class declarations."
    (interactive)
    (save-excursion
      (goto-char (point-min))
      (hs-hide-level 0))
    (message "Hide all blocks")
    )

  (defun python-hs-toggle-buffer ()
    "Toggle Hide-show status in Python.
  If called multiple times, the status will switch between `hide-all`,
  `show-outline`, `show-all`."
    (interactive)
    (unless (eq last-command 'python-hs-toggle-buffer)
      (setq hs-toggle-state 'hide-all)
      )
    (cond
     ((eq hs-toggle-state 'hide-all)
      (python-hs-top-level)
      (setq hs-toggle-state 'outline))
     ((eq hs-toggle-state 'outline)
      (python-hs-outline)
      (setq hs-toggle-state 'show-all))
     ((eq hs-toggle-state 'show-all)
      (python-hs-all)
      (setq hs-toggle-state 'hide-all))
     )
    )

  (add-hook 'python-mode-hook
            (lambda () (local-set-key
                        (kbd "C-<tab>")
                        'python-hs-toggle-buffer)))
#+end_src

***** Overlay style

Use special ellipsis than vanilla "..." for hided text, and show line
counts.

One of the reasons is the default symbol ~...~ may lead to ambiguity in
python, so a different representation shall be used.

#+begin_src emacs-lisp
  (defun python-hs-display-code-line-counts (ov)
    "Display custom indicator for hidden code indicated by OV."
    (let* ((ellipsis-str
  	  (format " %s " (if (and (char-displayable-p ?⤸)
  				  (char-displayable-p ?·))
  			     "··⤸" "...")))
  	 (nlines (- (count-lines (overlay-start ov) (overlay-end ov)) 1))
  	 (line-count-str (format "[%d %s]"
  				 nlines
  				 (if (eq nlines 1) "line" "lines")))
           (info (concat (propertize ellipsis-str
  				   'face
  				   'org-ellipsis)
  		       (propertize line-count-str
  				   'face
  				   '(:height 0.8 :inherit shadow))
  		       )))
      (overlay-put ov 'display info)))

  (add-hook 'python-mode-hook
            (lambda ()
              (setq-local hs-set-up-overlay
                          #'python-hs-display-code-line-counts)))
#+end_src

**** LSP
***** Setup

To use lsp, make sure ~python-lsp-server~ is installed to unlock the
full power of lsp-mode, by ~pip install python-lsp-server[all]~.

#+begin_src emacs-lisp
  (add-hook 'python-mode-hook 'lsp)
#+end_src

***** Grammar checker setting
****** Mypy cache directory

Define a directory for ~mypy~ temporarily files. Require ~pylsp-mypy~
package to install first to enable the lsp mypy checker.

#+begin_src emacs-lisp
  (setq lsp-pylsp-plugins-mypy-enabled t)
  (if (eq 'gnu/linux system-type)
      ;; For Linux system.
      (setq lsp-pylsp-plugins-mypy-overrides
  	  [t "--cache-dir=/home/collie/.emacs_backups/.mypy_cache/"])
    ;; For Windows system.
    (setq lsp-pylsp-plugins-mypy-overrides
  	[t "--cache-dir=C:/cache/.mypy_cache/"])
    )
#+end_src

****** COMMENT Disable docstyle check

Disable docstyle check. Sometimes it's too annoying.

#+begin_src emacs-lisp
    ;(setq lsp-pylsp-plugins-pydocstyle-enabled nil)
    ;(setq lsp-pylsp-plugins-pydocstyle-ignore ["D100" "D101" "D102"])
#+end_src

**** Highlight indentation

Enable highlight indentation for python.

#+begin_src emacs-lisp
  (add-hook 'python-mode-hook #'highlight-indentation-mode)
#+end_src

**** Pyvenv

Automatically enable python venv if ~.venv~ is found.

#+begin_src emacs-lisp
  (use-package pyvenv
    :ensure t
    :config
    (pyvenv-mode 1)
    (add-hook 'python-mode-hook
              (lambda ()
                (let ((venv (locate-dominating-file
  			   default-directory ".venv")))
                  (when venv
                    (pyvenv-activate
  		   (expand-file-name ".venv" venv)))))))
#+end_src

**** Dap mode

Using dap mode for python. Lsp is a mandatory for this mode. See
[[https://emacs-lsp.github.io/dap-mode/page/configuration/#python][official website]] for more details.

#+begin_src emacs-lisp
  (require 'dap-python)
  ;; if you installed debugpy, you need to set this
  ;; https://github.com/emacs-lsp/dap-mode/issues/306
  (setq dap-python-debugger 'debugpy)
#+end_src

*** Functions and key bindings
**** ShiftBlocks

Navigation functions taken from ~elpy~.

***** Shift left-and-right
#+begin_src emacs-lisp
  (defun elpy-nav-normalize-region ()
    "If the first or last line are not fully selected, select them
  completely."
    (let ((beg (region-beginning))
          (end (region-end)))
      (goto-char beg)
      (beginning-of-line)
      (push-mark (point) nil t)
      (goto-char end)
      (unless (= (point) (line-beginning-position))
        (end-of-line))))

  (defun elpy-nav-indent-shift-right (&optional _count)
    "Shift current line by COUNT columns to the right.

  COUNT defaults to `python-indent-offset'.
  If region is active, normalize the region and shift."
    (interactive)
    (if (use-region-p)
        (progn
          (elpy-nav-normalize-region)
          (python-indent-shift-right
  	 (region-beginning) (region-end) current-prefix-arg))
      (python-indent-shift-right
       (line-beginning-position) (line-end-position) current-prefix-arg)))

  (defun elpy-nav-indent-shift-left (&optional _count)
    "Shift current line by COUNT columns to the left.

  COUNT defaults to `python-indent-offset'.
  If region is active, normalize the region and shift."
    (interactive)
    (if (use-region-p)
        (progn
          (elpy-nav-normalize-region)
          (python-indent-shift-left
  	 (region-beginning) (region-end) current-prefix-arg))
      (python-indent-shift-left
       (line-beginning-position) (line-end-position) current-prefix-arg)))
#+end_src

***** Shift up-and-down

#+begin_src emacs-lisp
  (defun elpy-nav-move-line-or-region-down (&optional beg end)
    "Move the current line or active region down."
    (interactive
     (if (use-region-p)
         (list (region-beginning) (region-end))
       (list nil nil)))
    (if beg
        (elpy--nav-move-region-vertically beg end 1)
      (elpy--nav-move-line-vertically 1)))

  (defun elpy-nav-move-line-or-region-up (&optional beg end)
    "Move the current line or active region down."
    (interactive
     (if (use-region-p)
         (list (region-beginning) (region-end))
       (list nil nil)))
    (if beg
        (elpy--nav-move-region-vertically beg end -1)
      (elpy--nav-move-line-vertically -1)))

  (defun elpy--nav-move-line-vertically (dir)
    "Move the current line vertically in direction DIR."
    (let* ((beg (point-at-bol))
           (end (point-at-bol 2))
           (col (current-column))
           (region (delete-and-extract-region beg end)))
      (forward-line dir)
      (save-excursion
        (insert region))
      (goto-char (+ (point) col))))

  (defun elpy--nav-move-region-vertically (beg end dir)
    "Move the current region vertically in direction DIR."
    (let* ((point-before-mark (< (point) (mark)))
           (beg (save-excursion
                  (goto-char beg)
                  (point-at-bol)))
           (end (save-excursion
                  (goto-char end)
                  (if (bolp)
                      (point)
                    (point-at-bol 2))))
           (region (delete-and-extract-region beg end)))
      (goto-char beg)
      (forward-line dir)
      (save-excursion
        (insert region))
      (if point-before-mark
          (set-mark (+ (point)
                       (length region)))
        (set-mark (point))
        (goto-char (+ (point)
                      (length region))))
      (setq deactivate-mark nil)))
#+end_src

***** Keybindings

#+begin_src emacs-lisp
  (add-hook 'python-mode-hook
            (lambda () (local-set-key
                        (kbd "M-<down>")
                        'elpy-nav-move-line-or-region-down)))

  (add-hook 'python-mode-hook
            (lambda () (local-set-key
                        (kbd "M-<up>")
                        'elpy-nav-move-line-or-region-up)))

  (add-hook 'python-mode-hook
            (lambda () (local-set-key
                        (kbd "M-<left>")
                        'elpy-nav-indent-shift-left)))

  (add-hook 'python-mode-hook
            (lambda () (local-set-key
                        (kbd "M-<right>")
                        'elpy-nav-indent-shift-right)))
#+end_src

**** Python run buffer or region
***** Helper functions

These are the helper functions.

#+begin_src emacs-lisp
  (defun python-check-shell-ready ()
    "Check if the python shell is ready."
    (accept-process-output (get-buffer-process (python-shell-get-buffer)) 1))

  (defun python-shell-stop-process ()
    "Stop the running python process."
    (let ((pybuf (python-shell-get-buffer))
  	(i 0))
      (when pybuf
        (with-current-buffer pybuf
  	(comint-kill-subjob)))
      ;; Wait a maximum of 1.0s.
      (while (and (process-live-p (get-buffer-process pybuf)) (< i 10))
        (sleep-for 0.1)
        (setq i (+ i 1))
        )
      )
    )

  (defun python-run-buffer-or-selected-region-helper (&optional send-main)
    "Run the current buffer or the selected region."
    (let ((default-directory (or (projectile-project-root) default-directory)))
      (run-python)
      )
    (python-check-shell-ready)
    (if (use-region-p)
        (python-shell-send-region-with-echo (region-beginning) (region-end))
      (python-shell-send-buffer-with-echo (buffer-name) send-main)
      )
    (python-shell-switch-to-shell)
    )
#+end_src

***** Run buffer or selected region

Run the current buffer, or region if there's an active selected
region.  When running the current buffer, the ~__main__~ block will not
be executed unless a prefix argument is provided. Bind this funciton
to ~C-c C-c~.

#+begin_src emacs-lisp
  (defun python-run-buffer-or-selected-region ()
    "Run the current buffer or the selected region."
    (interactive)
    (python-run-buffer-or-selected-region-helper current-prefix-arg))

  (add-hook 'python-mode-hook
            (lambda () (local-set-key (kbd "C-c C-c")
                                      'python-run-buffer-or-selected-region)))
#+end_src

Press ~<f9>~ to run the whole buffer or the selected region.

#+begin_src emacs-lisp
  (add-hook 'python-mode-hook
            (lambda ()
              (local-set-key [f9] "\C-u\C-c\C-c")))
#+end_src

Press ~C-<f9>~ to kill the current python buffer and run the whole
buffer.

#+begin_src emacs-lisp

  (defun python-rerun () (interactive)
         "Kill python shell and run current buffer or selection."
         (python-shell-stop-process)
         (python-run-buffer-or-selected-region-helper '(4))
         )
  (add-hook 'python-mode-hook
            (lambda () (local-set-key (kbd "C-<f9>")
                                      'python-rerun)))
#+end_src

***** Save all and run buffer or selected region

Press ~<f5>~ to save all files, run the whole buffer or the selected
region.

#+begin_src emacs-lisp
  (add-hook 'python-mode-hook (lambda () (local-set-key
    [f5] (kbd "C-u C-x s C-u C-c C-c"))))
#+end_src

Press ~C-<f5>~ to save all files, kill the current python buffer and
run the whole buffer or the selected region.

#+begin_src emacs-lisp
  (defun python-save-and-rerun () (interactive)
         "Save all buffers, kill current python buffer and run
  current buffer or selection."
         (save-some-buffers '(4))
         (python-rerun)
         )
  (add-hook 'python-mode-hook
            (lambda () (local-set-key
                        (kbd "C-<f5>")
                        'python-save-and-rerun)))
#+end_src

**** Autopep8

Automatically formats Python code to conform the PEP 8 style
guide. To use this function in Python mode, press =M-x
autopep8=. The following code is inspired by [[https://gist.github.com/whirm/6122031][auto pep8 example]].

#+begin_src emacs-lisp
  ;; See https://gist.github.com/whirm/6122031 for reference.
  (defun autopep8 ()
    "Formats python code to conform the the PEP 8 style guide."
    (interactive)
    (cl-assert (eq major-mode 'python-mode) nil
               "can only use autopep8 in python-mode")
    (let ((orig-point (point)))
      (shell-command-on-region (point-min) (point-max)
                               "autopep8 - "
                               nil t)
      (python-mode)			; Revert highlights.
      (goto-char orig-point)
      )
    )
#+end_src

**** Unittest

Use ~C-c C-t~ to test the current test funciton or file, ~C-u C-c C-t~ to
test the whole project.

#+begin_src emacs-lisp
  (defun python-unittest (&optional whole-project)
    "Run Python unittest based on cursor position.

  If called without a prefix argument, run the current test method if the cursor is on one,
  otherwise run all tests in the current file. If called with a prefix argument (C-u),
  run the entire test suite using unittest discovery."
    (interactive "P")
    ;; (require 'projectile)     ; projectile is already required at startup
    (let* ((file (buffer-file-name))
           (func (python-info-current-defun))
           (project-root (projectile-project-root))
  	 (default-directory (or project-root default-directory))
           (relative-path (file-relative-name file project-root))
           (module-path (replace-regexp-in-string "/" "." (file-name-sans-extension relative-path)))
           (test-target
            (cond
             (whole-project "discover -v")
             ((and func (string-match "\\.test_" func))
              (format "%s.%s" module-path func))
             (t (concat module-path " -v")))))
      (compile (format "python -m unittest %s"
                       test-target))))

  ;; C-c C-t: Run the current test function or file depending on cursor position
  ;; C-u C-c C-t: Run the entire test suite for the project"
  (add-hook 'python-mode-hook
          (lambda ()
            (local-set-key (kbd "C-c C-t") #'python-unittest)))
#+end_src

*** Troubleshooting
**** Capabality with matplotlib on Windows machines

Matplotlib may not interactively plot figures in emacs environment on
Window systems. This also happens in babel mode. We have change the
interpreter to ipython by default on window OS, which relieves the
problem. However, user still needs to change the matplotlib's backend
to TtAgg (in ipython) to solve the problem. This can be done by adding
~matplotlib.use("TkAgg")~ after importing ~matplotlib~, or modify the
/matplotlibrc/ file by adding ~backend: TkAgg~, or set the system's
environment variable ~MPLBACKEND~ to ~Tkagg~.

**** Multilingual environment

Python shell do not work well with windows system when utf-8
characters are used in the buffer. Alternatively, using
=(set-language-environment "UTF-8")= solves the problem if the path of
the source code file is ASCII encoded, but may ruin other modes. See
this [[https://github.com/jorgenschaefer/elpy/issues/1729#issuecomment-558204483][github issue]].

#+begin_src emacs-lisp
  (setenv "PYTHONIOENCODING" "utf-8")
  ;; (add-to-list 'process-coding-system-alist
  ;;              '("elpy" . (utf-8 . utf-8)))
  ;; (add-to-list 'process-coding-system-alist
  ;;              '("python" . (utf-8 . utf-8)))
  ;; (add-to-list 'process-coding-system-alist
  ;;              '("flake8" . (utf-8 . utf-8)))
#+end_src

**** Python lsp

Pylsp becomes very slow when dealing with large libraries such as Transformers, which can cause Emacs to freeze. Use Pyright instead. See setup instructions on [[https://emacs-lsp.github.io/lsp-pyright/][this site]].

#+begin_src emacs-lisp
  (use-package lsp-pyright
  :ensure t)

  (defun python-select-lsp ()
    "Choose between pylsp and pyright for python lsp."
    (if (and (locate-dominating-file default-directory "pyrightconfig.json")
  	   (executable-find "pyright-langserver"))
        (progn
  	(setq-local lsp-disabled-clients '(pylsp))
          (require 'lsp-pyright)
          (lsp-deferred))
      (setq-local lsp-disabled-clients '(pyright))
      (lsp-deferred))
    )

  (add-hook 'python-mode-hook #'python-select-lsp)
#+end_src

**** COMMENT Lsp issue

=lsp-find-definition= may be very slow or even timed out when
processing python files on Linux. A similar problem can be
found on [[https://emacs.stackexchange.com/a/68748/38157][stackexchange]] and may be solved by disable lsp's
file watcher. However, in Python-mode, it seems to be a
problem realated to the performance of mypy checker. I'm not
sure about it, and haven't found a solution.

#+begin_src emacs-lisp
  (setq lsp-enable-file-watchers nil)
#+end_src

** C++ mode
*** Basic settings
**** Use C++ mode

Use ~C++-mode~ for ~.h~ files.

#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
#+end_src

Use ~cpp-mode~ as name alias for ~c++-mode~.

#+begin_src emacs-lisp
  (defalias 'cpp-mode 'c++-mode)
#+end_src

**** Indentation

Use space for indentation.

#+begin_src emacs-lisp
  (add-hook 'c-mode-hook
            (lambda () (setq indent-tabs-mode nil)))
  (add-hook 'c++-mode-hook
            (lambda () (setq indent-tabs-mode nil)))
#+end_src

Do not indent namespace in c++ mode.

#+begin_src emacs-lisp
  (defun cancel-c++-namespace-indentation ()
    (c-set-offset 'innamespace [0]))
  (add-hook 'c++-mode-hook 'cancel-c++-namespace-indentation)
#+end_src

*** Minor mode settings
**** Lsp
***** Use ~lsp-mode~

Use lsp-mode.

#+begin_src emacs-lisp
  (add-hook 'c++-mode-hook 'lsp)
  (add-hook 'c-mode-hook 'lsp)
#+end_src

***** COMMENT Spell check

The lsp-mode will use its own lsp-checker for flycheck. Here we
disable this behaviour so that it uses c/c++-clang as its
default checker.

#+begin_src emacs-lisp
  (setq lsp-diagnostic-package :none)
#+end_src

***** Work with tramp

Enable lsp-mode when editing remote files. See [[https://github.com/syl20bnr/spacemacs/issues/13925][Gibhub topic]] and
[[https://emacs-lsp.github.io/lsp-mode/page/remote/][official website]] for more information.

#+begin_src emacs-lisp
  (with-eval-after-load 'lsp-mode
    (lsp-register-client
     (make-lsp-client
      :remote? t
      :new-connection (lsp-tramp-connection "clangd")
      :major-modes '(c-mode c++-mode)
      :server-id 'clangd-remote)))
#+end_src

** Rust mode
*** Basic settings
**** Use rust-mode

#+begin_src emacs-lisp
  (use-package rust-mode :ensure t :no-require t)
#+end_src

**** COMMENT Use rustic mode

Rustic mode is based on rust mode and provides additional features.

#+begin_src emacs-lisp
  (use-package rustic :ensure t :no-require t)
#+end_src

**** Indentation

Use space for indentation.

#+begin_src emacs-lisp
  (add-hook 'rust-mode-hook
             (lambda () (setq indent-tabs-mode nil)))
#+end_src

*** Minor mode settings
**** LSP

Using lsp needs manually installation of =rust-analyzer=. This can be
done by =rustup=: ~rustup component add rust-analyzer~.

#+begin_src emacs-lisp
(add-hook 'rust-mode-hook #'lsp)
#+end_src

**** Flycheck

Flycheck for rust mode needs installation and initializaion.

#+begin_src emacs-lisp
  (use-package flycheck-rust :ensure t :no-require t)
  ;; Not needed if rustic mode is enabled.
  (with-eval-after-load 'rust-mode
    (add-hook 'flycheck-mode-hook #'flycheck-rust-setup))
#+end_src

**** COMMENT Eglot

Compared with lsp, eglot currently cannot expand macros for rust.

***** Setup

Using eglot needs manually installation of =rust-analyzer=. This can be
done by =rustup=: ~rustup component add rust-analyzer~.  For more
information, see [[https://rust-analyzer.github.io/manual.html#emacs][rust-analyzer's website]].

#+begin_src emacs-lisp
(add-hook 'rust-mode-hook 'eglot-ensure)
#+end_src

***** Flycheck issues

Eglot uses flymake mode by default. So we disable flycheck mode here.

#+begin_src emacs-lisp
  (add-hook 'rust-mode-hook (lambda () (flycheck-mode -1)))
#+end_src

*** Functions and key bindings
**** Lsp
***** Macro expandsion

Use ~C-c m~ to expand rust macros.

#+begin_src emacs-lisp
  (add-hook 'rust-mode-hook
            (lambda () (local-set-key
                        (kbd "C-c m")
                        'lsp-rust-analyzer-expand-macro)))

#+end_src

***** Inlay hints

Use ~C-c i~ to show/hide inlay hints.

#+begin_src emacs-lisp
  (defun rust-inlay-hints () (interactive)
         "Switch between lsp-inlay-hints-mode."
         (if lsp-inlay-hints-mode
             (progn (lsp-inlay-hints-mode -1))
           ;; Else :a ) If first time to enable this mode
           (if (not lsp-inlay-hint-enable)
               (progn
                 (setq lsp-inlay-hint-enable t)
                 ;; Needs to restart lsp workspace to make inlay hints
                 ;; enabled.
                 (lsp-workspace-restart (lsp--read-workspace))
                 ;; (lsp-restart-workspace)
                 (lsp-inlay-hints-mode t)
                 )
             ;; Else :b ) If this mode has been turned on before
             (lsp-inlay-hints-mode t)
             )
           )
         )

  (setq lsp-rust-analyzer-display-parameter-hints t)
  (setq lsp-rust-analyzer-closure-capture-hints t)
  (setq lsp-rust-analyzer-closure-return-type-hints "always")

  (add-hook 'rust-mode-hook
            (lambda () (setq lsp-inlay-hint-enable nil)))
  (add-hook 'rust-mode-hook
            (lambda () (local-set-key
                        (kbd "C-c i")
                        'rust-inlay-hints)))
#+end_src

**** COMMENT Eglot
***** Inlay hints

Disable inlay hints by default, and use ~C-c i~ to show/hide inlay hints.

#+begin_src emacs-lisp
  (setq-default eglot-inlay-hints-mode nil)
  (add-hook 'rust-mode-hook
            (lambda () (local-set-key
                        (kbd "C-c i")
                        'eglot-inlay-hints-mode)))
#+end_src

**** My own functions
***** Rust compile

Press ~<f9>~ to save all buffers and run command ~rust-compile~.

#+begin_src emacs-lisp
  (defun rust-save-and-compile (&optional arg) (interactive "P")
         "Save all buffers, and run `rust-compile`."
         (save-some-buffers '(4))
         (rust-compile)
         )
  (add-hook 'rust-mode-hook
            (lambda () (local-set-key
                        (kbd "<f9>")
                        'rust-save-and-compile)))
#+end_src

Press ~C-<f9>~ to save all buffers and run command ~rust-compile-release~.

#+begin_src emacs-lisp
  (defun rust-save-and-compile-release () (interactive)
         "Save all buffers, and run `rust-compile-release`."
         (save-some-buffers '(4))
         (rust-compile-release))
  (add-hook 'rust-mode-hook
            (lambda () (local-set-key
                        (kbd "C-<f9>")
                        'rust-save-and-compile-release)))
#+end_src

***** Rust run

Press ~<f5>~ to save all buffers and run command ~rust-run~. If an prefix
argument is given, run command ~rust-run-clippy~.

#+begin_src emacs-lisp
  (defun rust-save-and-run (&optional arg) (interactive "P")
         "Save all buffers, and run `rust-run`."
         (save-some-buffers '(4))
         (if arg (rust-run-clippy)
           (rust-run))
         )
  (add-hook 'rust-mode-hook
            (lambda () (local-set-key
                        (kbd "<f5>")
                        'rust-save-and-run)))
#+end_src

Press ~C-<f5>~ to save all buffers and run command ~rust-run-release~.

#+begin_src emacs-lisp
  (defun rust-save-and-run-release () (interactive)
         "Save all buffers, and run `rust-run-release`."
         (save-some-buffers '(4))
         (rust-run-release))
  (add-hook 'rust-mode-hook
            (lambda () (local-set-key
                        (kbd "C-<f5>")
                        'rust-save-and-run-release)))
#+end_src

***** Rust test

Use ~C-c C-t~ for ~rust-test~.
#+begin_src emacs-lisp
  (add-hook 'rust-mode-hook (lambda () (local-set-key
    (kbd "C-c C-t") (kbd "C-u C-x s C-c C-c C-t"))))
#+end_src

*** Troubleshooting
**** Extract signature for rust-analyzer

When using hover signature in ~lsp-mode~, it extracts the first line
returned by ~rust-analyzer~ by default as specfied by ~specific
lsp-clients-extract-signature-on-hover~. However, the first line
returned by ~rust-analyzer~ is ususlly not the type signature, which is
not what I want. A basic solution is given on [[https://github.com/emacs-lsp/lsp-mode/pull/1740#issuecomment-1776493727][Github]], and a more
detailed discussion can be found on [[https://tony-zorman.com/posts/fixing-lsp-mode.html][this site]].

#+begin_src emacs-lisp
(defun syntax-highlight-string (str mode)
  "Syntax highlight STR in MODE."
  (with-temp-buffer
    (insert str)
    ;; We definitely don't want to call certain modes, so delay the mode's
    ;; hooks until we have removed them.
    (delay-mode-hooks (funcall mode))
    (-map #'funcall
          (--remove (-contains? '(lsp-mode lsp-deferred) it)
                    (-mapcat #'symbol-value delayed-mode-hooks)))
    ;; Now we can propertise the string.
    (font-lock-ensure)
    (buffer-string)))

;; do not cache the shitty result from rust-analyzer
(advice-add #'lsp-eldoc-function :after (lambda (&rest _) (setq lsp--hover-saved-bounds nil)))
(with-eval-after-load 'lsp-rust
  ;; extract and show short signature for rust-analyzer
  (cl-defmethod lsp-clients-extract-signature-on-hover (contents (_server-id (eql rust-analyzer)))
    (syntax-highlight-string
     (let* ((value (if lsp-use-plists (plist-get contents :value) (gethash "value" contents)))
            (groups (--partition-by (s-blank? it) (s-lines (s-trim value))))
            (mod-group (cond ((s-equals? "```rust" (car (-fifth-item groups))) (-third-item groups))
                             ((s-equals? "```rust" (car (-third-item groups))) (-first-item groups))
                             (t nil)))
            (cmt (if (null mod-group) "" (concat " // " (cadr mod-group))))
            (sig-group (cond ((s-equals? "```rust" (car (-fifth-item groups))) (-fifth-item groups))
                             ((s-equals? "```rust" (car (-third-item groups))) (-third-item groups))
                             (t (-first-item groups))))
            (sig (->> sig-group
                      (--drop-while (s-equals? "```rust" it))
                      (--take-while (not (s-equals? "```" it)))
                      (--map (s-replace-regexp "//.*" "" it))
                      (--map (s-trim it))
                      (s-join " "))))
       (lsp--render-element (concat "```rust\n" sig cmt "\n```")))
     'rust-mode))
  )
#+end_src
**** TODO Run doctest with generics on Windows
When running doctest, ~rust-mode~ will run ~cargo test --doc --package
/package-name/ -- /function-name/ --show-output~. When ~function-name~
contains generics, ~<T>~ will be translated into other things on windows
system, leading to failure of doctest.
#+begin_src emacs-lisp
  ;; Cannot find the entry of doctest.
  ;; No solution provided yet.

#+end_src
** Qml mode
*** Basic settings

Edit QT QML code.

#+begin_src emacs-lisp
  (use-package qml-mode
    :ensure t
    :mode "\\.qml\\'")
#+end_src

*** Minor mode settings
**** Indentation

Use space for indentation.

#+begin_src emacs-lisp
  (add-hook 'qml-mode-hook
            (lambda () (setq indent-tabs-mode nil)))
#+end_src

**** Lsp

Lsp mode settings for ~qml-mode~.

#+begin_src emacs-lisp
  ;; Start lsp for qml-mode only when qmlls exists.
  (add-hook 'qml-mode-hook
            (lambda ()
              (when (executable-find "qmlls")
                (lsp))))

  ;; Set path for qmlls executable.
  (setq qml-lsp-client-path "qmlls")

  (lsp-register-client
   (make-lsp-client
    :new-connection (lsp-stdio-connection (list qml-lsp-client-path))
    :major-modes '(qml-mode)
    :server-id 'qmlls))
#+end_src

**** Highlight indentation

Enable highlight indentation for qml.

#+begin_src emacs-lisp
  (add-hook 'qml-mode-hook
    	  (lambda ()
    	    (highlight-indentation-mode t)
    	    (highlight-indentation-set-offset 4)))
#+end_src

*** Functions and keybindings
**** Make from project root

Press ~[f9]~ for compiling in project root using makefile.

#+begin_src emacs-lisp
  (defun make-from-project-root ()
    "Run makefile from project root without confirmation."
    (interactive)
    (let ((default-directory (or (projectile-project-root default-directory))))
      (compile "make -k")
      )
    )

  (add-hook 'qml-mode-hook
            (lambda () (local-set-key [f9]
                                      'make-from-project-root)))
#+end_src

**** Save and make from project root

Press ~[f5]~ for saving and compiling in project root.

#+begin_src emacs-lisp
  (defun save-and-make-from-project-root ()
    "Save all buffers and run makefile from project root without confirmation."
    (interactive)
    (save-some-buffers '(4))
    (let ((default-directory (or (projectile-project-root default-directory))))
      (compile "make -k")
      )
    )

  (add-hook 'qml-mode-hook
            (lambda () (local-set-key [f5]
                                      'save-and-make-from-project-root)))
#+end_src

* Not only an editor
** Magit
Use magit to interacting with Git.

#+begin_src emacs-lisp
  (use-package magit :ensure t :no-require t)
#+end_src
** Vterm
Vterm is not for you [[https://github.com/akermu/emacs-libvterm/issues/12][if you are using Windows]].

#+begin_src emacs-lisp
  (unless (eq 'windows-nt system-type)
    (use-package vterm :ensure t :no-require t)
    )
#+end_src

** Aidermacs

Use the configuration table to setup aidermacs. Set value to ~default~
for default settings.

Note that for open-ai compatiable models, ~model~ should begin with
~openai/~, see [[https://docs.litellm.ai/docs/providers/openai_compatible][litellm page]] (as aider uses litellm as backend).

The environment variables should also be set for model endpoint and
api token. Due to security reason, it should not be listed here in the
table.

*** Configuration
#+CAPTION: Aider Configuration
#+NAME: aider-conf
| Field | Value                                     |
|-------+-------------------------------------------|
| path  | "C:/msys64/home/zni/.local/bin/aider.exe" |
| conf  | "~/.aider.conf.yml"                       |

*** Setup
Use Aidermacs for vibe coding. Make sure [[https://aider.chat/docs/install.html][aider]] is installed first.

#+begin_src emacs-lisp
  (use-package aidermacs :ensure t
    :bind (("C-c c" . aidermacs-transient-menu))
    :custom
    (aidermacs-default-chat-mode 'architect))
#+end_src

User settings for aider.

#+begin_src emacs-lisp :var config=aider-conf
  (let ((path (cadr (assoc "path" config)))
        (conf (cadr (assoc "conf" config))))
    (if (not (string-equal path "default"))
        (setq aidermacs-program path)
      )
    (if (not (string-equal conf "default"))
        (setq aidermacs-config-file conf)
      )
    )
#+end_src

** Ellama

#+begin_src emacs-lisp
    (use-package ellama
      :ensure t
      :bind ("C-c e" . ellama)
      :hook (org-ctrl-c-ctrl-c-hook . ellama-chat-send-last-message)
      :init
      (require 'llm-openai)
      (setopt openai-compatible-provider
              (make-llm-openai-compatible
               :key (getenv "OPENAI_API_KEY")
               :url (getenv "OPENAI_API_BASE")
               :chat-model "zai-org/GLM-5.3"
  	    ))
      (setopt ellama-provider openai-compatible-provider)
      (setopt ellama-auto-scroll t)
      :config
      (ellama-setup-agentic-coding)
      ;; (ellama-context-header-line-global-mode +1)
      ;; (ellama-session-header-line-global-mode +1)
      (setq ellama-debug t)
      )
    ;; 达到上下文窗口95%才触发压缩（默认80%）
  (setopt ellama-session-auto-compact-threshold-percent 95)
  ;; 保留最近4轮完整对话
  (setopt ellama-session-auto-compact-keep-last-turns 4)
  ;; 禁止短会话强行压缩（消除你看到的kept 0 turn日志）
  (setopt ellama-session-auto-compact-allow-fewer-kept-turns nil)
#+end_src

** Gptel
*** Basic settings
#+begin_src emacs-lisp
  (use-package gptel
  :ensure t
  :bind (("C-c g" . gptel)
         ("C-c G" . gptel-menu))
  :config
  (setq gptel-siliconflow
          (gptel-make-openai "siliconflow"
            :host "api.siliconflow.cn"
            :endpoint "/v1/chat/completions"
            :stream t
            :key (lambda () (getenv "OPENAI_API_KEY"))
            :models '(
  		    "zai-org/GLM-5.3"
  		    (Qwen/Qwen3.5-4B
  		     :mime-types ("image/jpeg" "image/png" "image/webp" "image/gif"))
  		    "deepseek-ai/DeepSeek-V3.2"
  		    )))

  (setq gptel-ollama
        (gptel-make-ollama "ollama"
          :host "localhost:11434"
          :stream t
          :models '(
  		  (qwen3.5:9b
  		   :mime-types ("image/jpeg" "image/png" "image/webp" "image/gif"))
  		  )))

  (setq gptel-ollama-openai
        (gptel-make-openai "ollama-openai"
  	:protocol "http"
  	:host "localhost:11434"
          :endpoint "/v1/chat/completions"
          :stream t
          :key "dummy" ; Provide any value. No check is performed.
          :models '(
  		  (qwen3.5:9b
  		   :mime-types ("image/jpeg" "image/png" "image/webp" "image/gif"))
  		  )))

  (setq gptel-backend gptel-siliconflow)
  (setq gptel-model 'zai-org/GLM-5.3)

  )
#+end_src

*** Tools
**** Tools from gptel-agent

~gptel~ has the capability of tool calling.

#+begin_src emacs-lisp
  (use-package gptel-agent
    :ensure t
    :config (gptel-agent-update)
    )
#+end_src

***** Troubleshooting

The gptel-agent uses the POSIX ~tree~ for tool ~glob~. However, ~tree~
refers to ~tree.com~ on Windows and behaves differently, which leads to
errors. A solution is to rewrite the tool with standard behavior for
the agent.

#+begin_src emacs-lisp
  (with-eval-after-load 'gptel-agent
    (defun gptel-agent--glob (pattern &optional path depth)
      "Find files matching PATTERN, pure elisp implementation (NO external tree command).
  PATTERN is a case-insensitive glob-style pattern to match filenames against.
  PATH is the optional directory to search (defaults to current directory).
  DEPTH limits recursion depth when provided (non-negative integer).
  Returns a string listing matching files with full paths, sorted by
  modification time.  If the output is too large (>20000 chars), it writes
  the full results to a temporary file and returns a truncated version with
  instructions to use `Read' for the full contents.
  Raises an error if PATTERN is empty, PATH is not readable."
      (when (string-empty-p pattern)
        (error "Error: pattern must not be empty"))
      (setq path (or path "."))
      (unless (and (file-readable-p path) (file-directory-p path))
        (error "Error: path %s is not readable" path))
      (let* ((root (expand-file-name path))
             (max-depth (if (natnump depth) depth nil))
             entries)
        (cl-labels
            ((walk (dir level)
               ;; guard: dir must be string and readable
               (when (and (stringp dir)
  			(file-readable-p dir)
  			(file-directory-p dir))
                 (dolist (f (directory-files dir t))
  		 (let* ((fname (file-name-nondirectory f))
  			(is-dir (file-directory-p f)))
                     (unless (member fname '("." ".."))
                       ;; collect every entry (file OR dir), then test pattern
                       (when (string-match-p (concat "^" (wildcard-to-regexp pattern) "$") fname)
                         (push f entries))
                       ;; recurse into subdirs, skip .git
                       (when (and is-dir
  				(not (equal fname ".git"))
  				(or (not max-depth) (< level max-depth)))
                         (walk f (1+ level)))))))))
  	;; tree -L N: root is level 1
  	(walk root 1))
        ;; build list with mtime for sorting, safely handle nil attributes
        (setq entries
              (mapcar (lambda (f)
                        (let ((attr (file-attributes f)))
  			(cons f (if attr (file-attribute-modification-time attr) (current-time)))))
                      entries))
        ;; sort by mtime ascending (oldest first)
        (setq entries (sort entries (lambda (a b) (time-less-p (cdr a) (cdr b)))))
        (with-temp-buffer
  	(dolist (e entries)
            (insert (car e) "\n"))
  	(gptel-agent--truncate-buffer "glob")
  	(buffer-string))))
    )
#+end_src

**** COMMENT User-defined tools

#+begin_src emacs-lisp
  (with-eval-after-load 'gptel
    (defun gptel-tool-now ()
      "Return current system time."
      (format-time-string "%Y-%m-%d %H:%M:%S %Z"))

    (setq gptel-tools
          (list
           (gptel-make-tool
            :name "now"
            :function #'gptel-tool-now
            :description "Get current date, time and timezone. You MUST call this tool when user asks what time it is."
            :args nil)))
#+end_src

** COMMENT Emacs application framework

Not fuly installed.

*** Setup

#+begin_src emacs-lisp
  (add-to-list 'load-path
               "~/.emacs.d/site-lisp/emacs-application-framework/")
  (require 'eaf)
  (require 'eaf-airshare)
  (require 'eaf-browser)
  (require 'eaf-camera)
#+end_src
